### ISSUE TITLE
ir_datasets missing requirement

### ISSUE THREAD

**Issue by AmenRa** [terrierteam/aolia-tools#1]
Hi, and thanks for this fantastic tool / dataset!

As written in the title, `ir_datasets` is not listed as a requirement, which makes `downloader.py` crash.

I do not open a PR as maybe you want to define a specific version for `ir_datasets`.
The current one is `0.5.1`.

Thanks again,

Elias

**Comment by seanmacavaney** [comment]
Nice spot, thanks Elias. It's been supported in irds since 0.5.0, so I'll add that to the requirements file.
